name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Files
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Build Ionic
        run: ionic build

      - name: Install Capacitor
        run: npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Add Android Platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JHAG-Hub-App
          path: android/app/build/outputs/apk/debug/*.apk